---
# local profile
spring:
  profiles: local

########################################################
### Data Source
########################################################
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

########################################################
### Java Persistence Api JPA
########################################################
  jpa:
    database: mysql
    show-sql: true

    # hibernate
    hibernate:
      naming:
        # hql命名策略
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# log
logging:
  config: "classpath:logback/logback-local.xml"
