---
# production profile
spring:
  profiles: production

  ########################################################
  ### Data Source
  ########################################################
  datasource:
    url: jdbc:mysql://rm-wz9dk976n5cchw7nn.mysql.rds.aliyuncs.com:3306/business
    username: user_001
    password: user_001
    driver-class-name: com.mysql.jdbc.Driver

  ########################################################
  ### Connection Pool
  ########################################################
  dbcp2:
    # 初始化连接池大小
    initial-size: 10
    # 配置最小连接池数
    min-idle: 10
    # 配置最大连接池数
    max-idle: 30
    # 配置获取超时连接的等待时间
    max-wait-millis: 30000
    # 配置多长时间进行一次检测,检测需要关闭的数据库连接
    time-between-eviction-runs-millis: 200000
    # 配置连接在连接池的最小生存时间
    remove-abandoned-on-maintenance: 200000

  ########################################################
  ### Java Persistence Api JPA
  ########################################################
  jpa:
    database: mysql
    show-sql: true
    # hibernate
    hibernate:
      naming:
        # hql命名策略
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# log
logging:
  config: "classpath:logback/logback-production.xml"
